version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: finanzas_db_dev
    environment:
      POSTGRES_DB: finanzas_db
      POSTGRES_USER: finanzas_user
      POSTGRES_PASSWORD: finanzas_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - finanzas_network_dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finanzas_backend_dev
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://finanzas_user:finanzas_password@postgres:5432/finanzas_db
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_WHATSAPP_NUMBER: ${TWILIO_WHATSAPP_NUMBER}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-your-secret-key-here}
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - finanzas_network_dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: finanzas_frontend_dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/tsconfig.app.json:/app/tsconfig.app.json
      - ./frontend/.env:/app/.env
      # Exclude node_modules from volume mounting
      - /app/node_modules
    networks:
      - finanzas_network_dev
    depends_on:
      - backend

volumes:
  postgres_data_dev:

networks:
  finanzas_network_dev:
    driver: bridge