[phases.setup]
nixPkgs = ['nodejs_20', 'python311']

[phases.install]
cmds = [
    'echo "Installing backend dependencies..."',
    'cd backend && pip install -r requirements.txt',
    'echo "Installing frontend dependencies..."', 
    'cd frontend && npm ci'
]

[phases.build]
cmds = [
    'echo "Building frontend..."',
    'cd frontend && npm run build',
    'echo "Frontend built successfully"'
]

[start]
cmd = 'cd backend && python railway_start.py'